### ISSUE TITLE
Keyboard LED

### ISSUE THREAD

**Issue by Jonson26** [RasmusB/USB-Keyboard-Adapter#6]
Is there a way to somehow control the keyboard LED?
Either as a caps lock indicator or something custom?

**Comment by RasmusB** [comment]
The keyboard itself does not have an LED - at least on the keyboards I have seen. There is a hole and a lens on the keyboard, meant for an LED on the motherboard to shine through. So basically you'll need to add your own LED somehow.

**Comment by Jonson26** [comment]
Aaah, great to know, thanks! I plan on using the keyboard with a raspberry pi, so this should be fairly easy to pull off.
